currentLine = function() {
  return Router.current().params.line;
};

currentTransitType = function() {
  return Router.current().params.type;
};

currentStations = function () {
  return stations[currentLine()];
};

stations = {
  'Red Line - Northbound': [
    {name: 'Alewife'},
    {name: 'Davis'},
    {name: 'Porter Square'},
    {name: 'Harvard Square'},
    {name: 'Central Square'},
    {name: 'Kendall'},
    {name: 'Charles/MGH'},
    {name: 'Park Street'},
    {name: 'Downtown Crossing'},
    {name: 'South Station'},
    {name: 'Broadway'},
    {name: 'Andrew'},
    {name: 'JFK/UMass'},
    {name: 'North Quincy'},
    {name: 'Wollaston'},
    {name: 'Quincy Center'},
    {name: 'Quincy Adams'},
    {name: 'Braintree'},
    {name: 'Savin Hill'},
    {name: 'Fields Corner'},
    {name: 'Shawmut'},
    {name: 'Ashmont'}
  ],
  'Red Line - Southbound': [
    {name: 'Alewife'},
    {name: 'Davis'},
    {name: 'Porter Square'},
    {name: 'Harvard Square'},
    {name: 'Central Square'},
    {name: 'Kendall'},
    {name: 'Charles/MGH'},
    {name: 'Park Street'},
    {name: 'Downtown Crossing'},
    {name: 'South Station'},
    {name: 'Broadway'},
    {name: 'Andrew'},
    {name: 'JFK/UMass'},
    {name: 'North Quincy'},
    {name: 'Wollaston'},
    {name: 'Quincy Center'},
    {name: 'Quincy Adams'},
    {name: 'Braintree'},
    {name: 'Savin Hill'},
    {name: 'Fields Corner'},
    {name: 'Shawmut'},
    {name: 'Ashmont'}
  ],
  'Orange Line - Northbound': [
    {name: 'Oak Grove'},
    {name: 'Malden Center'},
    {name: 'Wellington'},
    {name: 'Assembly'},
    {name: 'Sullivan Square'},
    {name: 'Community College'},
    {name: 'North Station'},
    {name: 'Haymarket'},
    {name: 'State Street'},
    {name: 'Downtown Crossing'},
    {name: 'Chinatown'},
    {name: 'Tufts Medical Center'},
    {name: 'Back Bay'},
    {name: 'Massachusetts Ave.'},
    {name: 'Ruggles'},
    {name: 'Roxbury Crossing'},
    {name: 'Jackson Square'},
    {name: 'Stony Brook'},
    {name: 'Green Street'},
    {name: 'Forest Hills'}
  ],
  'Orange Line - Southbound': [
    {name: 'Oak Grove'},
    {name: 'Malden Center'},
    {name: 'Wellington'},
    {name: 'Assembly'},
    {name: 'Sullivan Square'},
    {name: 'Community College'},
    {name: 'North Station'},
    {name: 'Haymarket'},
    {name: 'State Street'},
    {name: 'Downtown Crossing'},
    {name: 'Chinatown'},
    {name: 'Tufts Medical Center'},
    {name: 'Back Bay'},
    {name: 'Massachusetts Ave.'},
    {name: 'Ruggles'},
    {name: 'Roxbury Crossing'},
    {name: 'Jackson Square'},
    {name: 'Stony Brook'},
    {name: 'Green Street'},
    {name: 'Forest Hills'}
  ],
  'Blue Line - Northbound': [
    {name: 'Wonderland'},
    {name: 'Revere Beach'},
    {name: 'Beachmont'},
    {name: 'Suffolk Downs'},
    {name: 'Orient Heights'},
    {name: 'Wood Island'},
    {name: 'Airport'},
    {name: 'Maverick'},
    {name: 'Aquarium'},
    {name: 'State'},
    {name: 'Bowdoin'}
  ],
  'Blue Line - Southbound': [
    {name: 'Wonderland'},
    {name: 'Revere Beach'},
    {name: 'Beachmont'},
    {name: 'Suffolk Downs'},
    {name: 'Orient Heights'},
    {name: 'Wood Island'},
    {name: 'Airport'},
    {name: 'Maverick'},
    {name: 'Aquarium'},
    {name: 'State'},
    {name: 'Bowdoin'}
  ],
  'Green Line B - Westbound': [
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Hynes Convention Center'},
    {name: 'Kenmore'},
    {name: 'Blandford Street'},
    {name: 'Boston Univ. East'},
    {name: 'Boston Univ. Central'},
    {name: 'Boston Univ. West'},
    {name: 'Saint Paul Street'},
    {name: 'Pleasant Street'},
    {name: 'Babcock Street'},
    {name: 'Packards Corner'},
    {name: 'Harvard Ave.'},
    {name: 'Griggs Street'},
    {name: 'Allston Street'},
    {name: 'Warren Street'},
    {name: 'Washington Street'},
    {name: 'Sutherland Road'},
    {name: 'Chiswick Road'},
    {name: 'Chestnut Hill Ave.'},
    {name: 'South Street'},
    {name: 'Boston College'}
  ],
  'Green Line B - Eastbound': [
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Hynes Convention Center'},
    {name: 'Kenmore'},
    {name: 'Blandford Street'},
    {name: 'Boston Univ. East'},
    {name: 'Boston Univ. Central'},
    {name: 'Boston Univ. West'},
    {name: 'Saint Paul Street'},
    {name: 'Pleasant Street'},
    {name: 'Babcock Street'},
    {name: 'Packards Corner'},
    {name: 'Harvard Ave.'},
    {name: 'Griggs Street'},
    {name: 'Allston Street'},
    {name: 'Warren Street'},
    {name: 'Washington Street'},
    {name: 'Sutherland Road'},
    {name: 'Chiswick Road'},
    {name: 'Chestnut Hill Ave.'},
    {name: 'South Street'},
    {name: 'Boston College'}
  ],
  'Green Line C - Westbound': [
    {name: 'North Station'},
    {name: 'Haymarket'},
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Hynes Convention Center'},
    {name: 'Kenmore'},
    {name: 'Saint Mary Street'},
    {name: 'Hawes Street'},
    {name: 'Kent Street'},
    {name: 'Saint Paul Street'},
    {name: 'Coolidge Corner'},
    {name: 'Summit Ave.'},
    {name: 'Brandon Hall'},
    {name: 'Fairbanks Street'},
    {name: 'Washington Square'},
    {name: 'Tappan Street'},
    {name: 'Dean Road'},
    {name: 'Englewood Ave.'},
    {name: 'Cleveland Circle'}
  ],
  'Green Line C - Eastbound': [
    {name: 'North Station'},
    {name: 'Haymarket'},
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Hynes Convention Center'},
    {name: 'Kenmore'},
    {name: 'Saint Mary Street'},
    {name: 'Hawes Street'},
    {name: 'Kent Street'},
    {name: 'Saint Paul Street'},
    {name: 'Coolidge Corner'},
    {name: 'Summit Ave.'},
    {name: 'Brandon Hall'},
    {name: 'Fairbanks Street'},
    {name: 'Washington Square'},
    {name: 'Tappan Street'},
    {name: 'Dean Road'},
    {name: 'Englewood Ave.'},
    {name: 'Cleveland Circle'}
  ],
  'Green Line D - Westbound': [
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Hynes Convention Center'},
    {name: 'Kenmore'},
    {name: 'Fenway'},
    {name: 'Longwood'},
    {name: 'Brookline Village'},
    {name: 'Brookline Hills'},
    {name: 'Beaconsfield'},
    {name: 'Reservoir'},
    {name: 'Chestnut Hill'},
    {name: 'Newton Centre'},
    {name: 'Newton Highlands'},
    {name: 'Eliot'},
    {name: 'Waban'},
    {name: 'Woodland'},
    {name: 'Riverside'}
  ],
  'Green Line D - Eastbound': [
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Hynes Convention Center'},
    {name: 'Kenmore'},
    {name: 'Fenway'},
    {name: 'Longwood'},
    {name: 'Brookline Village'},
    {name: 'Brookline Hills'},
    {name: 'Beaconsfield'},
    {name: 'Reservoir'},
    {name: 'Chestnut Hill'},
    {name: 'Newton Centre'},
    {name: 'Newton Highlands'},
    {name: 'Eliot'},
    {name: 'Waban'},
    {name: 'Woodland'},
    {name: 'Riverside'}
  ],
  'Green Line E - Westbound': [
    {name: 'Lechmere'},
    {name: 'Science Park'},
    {name: 'North Station'},
    {name: 'Haymarket'},
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Prudential'},
    {name: 'Symphony'},
    {name: 'Northeastern University'},
    {name: 'Museum of Fine Arts'},
    {name: 'Longwood Medical Area'},
    {name: 'Brigham Circle'},
    {name: 'Fenwood Road'},
    {name: 'Mission Park'},
    {name: 'Riverway'},
    {name: 'Back of the Hill'},
    {name: 'Heath Street'}
  ],
  'Green Line E - Eastbound': [
    {name: 'Lechmere'},
    {name: 'Science Park'},
    {name: 'North Station'},
    {name: 'Haymarket'},
    {name: 'Park Street'},
    {name: 'Boylston'},
    {name: 'Arlington'},
    {name: 'Copley'},
    {name: 'Prudential'},
    {name: 'Symphony'},
    {name: 'Northeastern University'},
    {name: 'Museum of Fine Arts'},
    {name: 'Longwood Medical Area'},
    {name: 'Brigham Circle'},
    {name: 'Fenwood Road'},
    {name: 'Mission Park'},
    {name: 'Riverway'},
    {name: 'Back of the Hill'},
    {name: 'Heath Street'}
  ],
  'Fairmount Line - Inbound': [
    {name: 'Readville'},
    {name: 'Fairmount'},
    {name: 'Morton St.'},
    {name: 'Talbot Ave.'},
    {name: 'Four Corners/Geneva Ave.'},
    {name: 'Uphams Corner'},
    {name: 'Newmarket'},
    {name: 'South Station'}
  ],
  'Fairmount Line - Outbound': [
    {name: 'Readville'},
    {name: 'Fairmount'},
    {name: 'Morton St.'},
    {name: 'Talbot Ave.'},
    {name: 'Four Corners/Geneva Ave.'},
    {name: 'Uphams Corner'},
    {name: 'Newmarket'},
    {name: 'South Station'}
  ],
  'Fitchburg Line - Inbound': [
    {name: 'Fitchburg'},
    {name: 'N. Leominster'},
    {name: 'Shirley'},
    {name: 'Ayer'},
    {name: 'Littleton/495'},
    {name: 'S. Acton'},
    {name: 'W. Concord'},
    {name: 'Concord'},
    {name: 'Lincoln'},
    {name: 'Silver Hill'},
    {name: 'Hastings'},
    {name: 'Kendal Green'},
    {name: 'Brandeis/Roberts'},
    {name: 'Waltham'},
    {name: 'Waverley'},
    {name: 'Belmont'},
    {name: 'Porter Sq.'},
    {name: 'North Station'}
  ],
  'Fitchburg Line - Outbound': [
    {name: 'Fitchburg'},
    {name: 'N. Leominster'},
    {name: 'Shirley'},
    {name: 'Ayer'},
    {name: 'Littleton/495'},
    {name: 'S. Acton'},
    {name: 'W. Concord'},
    {name: 'Concord'},
    {name: 'Lincoln'},
    {name: 'Silver Hill'},
    {name: 'Hastings'},
    {name: 'Kendal Green'},
    {name: 'Brandeis/Roberts'},
    {name: 'Waltham'},
    {name: 'Waverley'},
    {name: 'Belmont'},
    {name: 'Porter Sq.'},
    {name: 'North Station'}
  ],
  'Framingham-Worcester Line - Inbound': [
    {name: 'Worcester'},
    {name: 'Grafton'},
    {name: 'Westborough'},
    {name: 'Southborough'},
    {name: 'Ashland'},
    {name: 'Framingham'},
    {name: 'W. Natick'},
    {name: 'Natick Center'},
    {name: 'Wellesley Sq.'},
    {name: 'Wellesley Hills'},
    {name: 'Wellesley Farms'},
    {name: 'Auburndale'},
    {name: 'W. Newton'},
    {name: 'Newtonville'},
    {name: 'Yawkey'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Framingham-Worcester Line - Outbound': [
    {name: 'Worcester'},
    {name: 'Grafton'},
    {name: 'Westborough'},
    {name: 'Southborough'},
    {name: 'Ashland'},
    {name: 'Framingham'},
    {name: 'W. Natick'},
    {name: 'Natick Center'},
    {name: 'Wellesley Sq.'},
    {name: 'Wellesley Hills'},
    {name: 'Wellesley Farms'},
    {name: 'Auburndale'},
    {name: 'W. Newton'},
    {name: 'Newtonville'},
    {name: 'Yawkey'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Lowell Line - Inbound': [
    {name: 'Lowell'},
    {name: 'North Billerica'},
    {name: 'Haverhill'},
    {name: 'Wilmington'},
    {name: 'Anderson/Woburn'},
    {name: 'Mishawum'},
    {name: 'Winchester Center'},
    {name: 'Wedgemere'},
    {name: 'West Medford'},
    {name: 'North Station'}
  ],
  'Lowell Line - Outbound': [
    {name: 'Lowell'},
    {name: 'North Billerica'},
    {name: 'Haverhill'},
    {name: 'Wilmington'},
    {name: 'Anderson/Woburn'},
    {name: 'Mishawum'},
    {name: 'Winchester Center'},
    {name: 'Wedgemere'},
    {name: 'West Medford'},
    {name: 'North Station'}
  ],
  'Middleborough-Lakeville Line - Inbound': [
    {name: 'Middleborough/Lakeville'},
    {name: 'Bridgewater'},
    {name: 'Campello'},
    {name: 'Brockton'},
    {name: 'Montello'},
    {name: 'Holbrook/Randolph'},
    {name: 'Braintree'},
    {name: 'Quincy Center'},
    {name: 'JFK/UMass'},
    {name: 'South Station'}
  ],
  'Middleborough-Lakeville Line - Outbound': [
    {name: 'Middleborough/Lakeville'},
    {name: 'Bridgewater'},
    {name: 'Campello'},
    {name: 'Brockton'},
    {name: 'Montello'},
    {name: 'Holbrook/Randolph'},
    {name: 'Braintree'},
    {name: 'Quincy Center'},
    {name: 'JFK/UMass'},
    {name: 'South Station'}
  ],
  'Needham Line - Inbound': [
    {name: 'Needham Heights'},
    {name: 'Needham Center'},
    {name: 'Needham Junction'},
    {name: 'Hersey'},
    {name: 'West Roxbury'},
    {name: 'Highland'},
    {name: 'Bellevue'},
    {name: 'Roslindale Village'},
    {name: 'Forest Hills'},
    {name: 'Ruggles'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Needham Line - Outbound': [
    {name: 'Needham Heights'},
    {name: 'Needham Center'},
    {name: 'Needham Junction'},
    {name: 'Hersey'},
    {name: 'West Roxbury'},
    {name: 'Highland'},
    {name: 'Bellevue'},
    {name: 'Roslindale Village'},
    {name: 'Forest Hills'},
    {name: 'Ruggles'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Franklin Line - Inbound': [
    {name: 'Forge Park/495'},
    {name: 'Franklin'},
    {name: 'Norfolk'},
    {name: 'Walpole'},
    {name: 'Plimptonville'},
    {name: 'Windsor Gardens'},
    {name: 'Norwood Central'},
    {name: 'Norwood Depot'},
    {name: 'Islington'},
    {name: 'Dedham Corp. Center'},
    {name: 'Endicott'},
    {name: 'Readville'},
    {name: 'Hyde Park'},
    {name: 'Ruggles'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Franklin Line - Outbound': [
    {name: 'Forge Park/495'},
    {name: 'Franklin'},
    {name: 'Norfolk'},
    {name: 'Walpole'},
    {name: 'Plimptonville'},
    {name: 'Windsor Gardens'},
    {name: 'Norwood Central'},
    {name: 'Norwood Depot'},
    {name: 'Islington'},
    {name: 'Dedham Corp. Center'},
    {name: 'Endicott'},
    {name: 'Readville'},
    {name: 'Hyde Park'},
    {name: 'Ruggles'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Greenbush Line - Inbound': [
    {name: 'Greenbush'},
    {name: 'North Scituate'},
    {name: 'Cohasset'},
    {name: 'Nantasket Junction'},
    {name: 'West Hingham'},
    {name: 'East Weymouth'},
    {name: 'Weymouth Landing/East Braintree'},
    {name: 'Quincy Center'},
    {name: 'JFK/UMass'},
    {name: 'South Station'}
  ],
  'Greenbush Line - Outbound': [
    {name: 'Greenbush'},
    {name: 'North Scituate'},
    {name: 'Cohasset'},
    {name: 'Nantasket Junction'},
    {name: 'West Hingham'},
    {name: 'East Weymouth'},
    {name: 'Weymouth Landing/East Braintree'},
    {name: 'Quincy Center'},
    {name: 'JFK/UMass'},
    {name: 'South Station'}
  ],
  'Kingston-Plymouth Line - Inbound': [
    {name: 'Kingston'},
    {name: 'Plymouth'},
    {name: 'Halifax'},
    {name: 'Hanson'},
    {name: 'Whitman'},
    {name: 'Abington'},
    {name: 'South Weymouth'},
    {name: 'Braintree'},
    {name: 'JFK/UMass'},
    {name: 'South Station'}
  ],
  'Kingston-Plymouth Line - Outbound': [
    {name: 'Kingston'},
    {name: 'Plymouth'},
    {name: 'Halifax'},
    {name: 'Hanson'},
    {name: 'Whitman'},
    {name: 'Abington'},
    {name: 'South Weymouth'},
    {name: 'Braintree'},
    {name: 'JFK/UMass'},
    {name: 'South Station'}
  ],
  'Newburyport-Rockport Line - Inbound': [
    {name: 'Rockport'},
    {name: 'Gloucester'},
    {name: 'West Gloucester'},
    {name: 'Manchester'},
    {name: 'Beverly Farms'},
    {name: 'Prides Crossing'},
    {name: 'Montserrat'},
    {name: 'Newburyport'},
    {name: 'Rowley'},
    {name: 'Ipswich'},
    {name: 'Hamilton/Wenham'},
    {name: 'North Beverly'},
    {name: 'Beverly'},
    {name: 'Salem'},
    {name: 'Swampscott'},
    {name: 'Lynn'},
    {name: 'River Works'},
    {name: 'Chelsea'},
    {name: 'North Station'}
  ],
  'Newburyport-Rockport Line - Outbound': [
    {name: 'Rockport'},
    {name: 'Gloucester'},
    {name: 'West Gloucester'},
    {name: 'Manchester'},
    {name: 'Beverly Farms'},
    {name: 'Prides Crossing'},
    {name: 'Montserrat'},
    {name: 'Newburyport'},
    {name: 'Rowley'},
    {name: 'Ipswich'},
    {name: 'Hamilton/Wenham'},
    {name: 'North Beverly'},
    {name: 'Beverly'},
    {name: 'Salem'},
    {name: 'Swampscott'},
    {name: 'Lynn'},
    {name: 'River Works'},
    {name: 'Chelsea'},
    {name: 'North Station'}
  ],
  'Providence-Stoughton Line - Inbound': [
    {name: 'Wickford Junction'},
    {name: 'TF Green Airport'},
    {name: 'Providence'},
    {name: 'South Attleboro'},
    {name: 'Mansfield'},
    {name: 'Sharon'},
    {name: 'Stoughton'},
    {name: 'Canton Center'},
    {name: 'Route 128'},
    {name: 'Hyde Park'},
    {name: 'Ruggles'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Providence-Stoughton Line - Outbound': [
    {name: 'Wickford Junction'},
    {name: 'TF Green Airport'},
    {name: 'Providence'},
    {name: 'South Attleboro'},
    {name: 'Mansfield'},
    {name: 'Sharon'},
    {name: 'Stoughton'},
    {name: 'Canton Center'},
    {name: 'Route 128'},
    {name: 'Hyde Park'},
    {name: 'Ruggles'},
    {name: 'Back Bay'},
    {name: 'South Station'}
  ],
  'Haverhill Line - Inbound': [
    {name: 'Haverhill'},
    {name: 'Bradford'},
    {name: 'Lawrence'},
    {name: 'Andover'},
    {name: 'Ballardvale'},
    {name: 'North Wilmington'},
    {name: 'Wilmington'},
    {name: 'Anderson/Woburn'},
    {name: 'Reading'},
    {name: 'Wakefield'},
    {name: 'Greenwood'},
    {name: 'Melrose Highlands'},
    {name: 'Melrose Cedar Park'},
    {name: 'Wyoming Hill'},
    {name: 'Malden Center'},
    {name: 'North Station'}
  ],
  'Haverhill Line - Outbound': [
    {name: 'Haverhill'},
    {name: 'Bradford'},
    {name: 'Lawrence'},
    {name: 'Andover'},
    {name: 'Ballardvale'},
    {name: 'North Wilmington'},
    {name: 'Wilmington'},
    {name: 'Anderson/Woburn'},
    {name: 'Reading'},
    {name: 'Wakefield'},
    {name: 'Greenwood'},
    {name: 'Melrose Highlands'},
    {name: 'Melrose Cedar Park'},
    {name: 'Wyoming Hill'},
    {name: 'Malden Center'},
    {name: 'North Station'}
  ],
  'SL1 - Inbound': [
    {name: 'Terminal A'},
    {name: 'Terminal B - Stop 1'},
    {name: 'Terminal B - Stop 2'},
    {name: 'Terminal C'},
    {name: 'Terminal E'},
    {name: 'Silver Line Way'},
    {name: 'World Trade Center'},
    {name: 'Court House'},
    {name: 'South Station'}
  ],
  'SL1 - Outbound': [
    {name: 'Terminal A'},
    {name: 'Terminal B - Stop 1'},
    {name: 'Terminal B - Stop 2'},
    {name: 'Terminal C'},
    {name: 'Terminal E'},
    {name: 'Silver Line Way'},
    {name: 'World Trade Center'},
    {name: 'Court House'},
    {name: 'South Station'}
  ],
  'SL2 - Inbound': [
    {name: 'Design Center'},
    {name: 'Northern Ave & Tide St'},
    {name: 'Silver Line Way'},
    {name: 'World Trade Center'},
    {name: 'Court House'},
    {name: 'South Station'}
  ],
  'SL2 - Outbound': [
    {name: 'Design Center'},
    {name: 'Northern Ave & Tide St'},
    {name: 'Silver Line Way'},
    {name: 'World Trade Center'},
    {name: 'Court House'},
    {name: 'South Station'}
  ],
  'SL4 - Inbound': [
    {name: 'Dudley Station'},
    {name: 'Washington St & Melnea Cass Blvd'},
    {name: 'Washington St & Lenox St'},
    {name: 'Washington St & Massachusetts Ave'},
    {name: 'Washington St & Worcester St'},
    {name: 'Washington St & E Newton St'},
    {name: 'Washington St & Union Pk'},
    {name: 'Washington St & E Berkeley St'},
    {name: 'Washington St & Herald St'},
    {name: 'Washington St & Tufts Med Ctr'},
    {name: 'Washington St & Essex St'},
    {name: 'Essex St & Atlantic Ave'}
  ],
  'SL4 - Outbound': [
    {name: 'Dudley Station'},
    {name: 'Washington St & Melnea Cass Blvd'},
    {name: 'Washington St & Lenox St'},
    {name: 'Washington St & Massachusetts Ave'},
    {name: 'Washington St & Worcester St'},
    {name: 'Washington St & E Newton St'},
    {name: 'Washington St & Union Pk'},
    {name: 'Washington St & E Berkeley St'},
    {name: 'Washington St & Herald St'},
    {name: 'Washington St & Tufts Med Ctr'},
    {name: 'Essex St & Atlantic Ave'}
  ],
  'SL5 - Inbound': [
    {name: 'Dudley Station'},
    {name: 'Washington St & Melnea Cass Blvd'},
    {name: 'Washington St & Lenox St'},
    {name: 'Washington St & Massachusetts Ave'},
    {name: 'Washington St & Worcester St'},
    {name: 'Washington St & E Newton St'},
    {name: 'Washington St & Union Pk'},
    {name: 'Washington St & E Berkeley St'},
    {name: 'Washington St & Herald St'},
    {name: 'Washington St & Tufts Med Ctr'},
    {name: 'Washington St & Essex St'},
    {name: 'Temple Pl & Washington St'}
  ],
  'SL5 - Outbound': [
    {name: 'Dudley Station'},
    {name: 'Washington St & Melnea Cass Blvd'},
    {name: 'Washington St & Lenox St'},
    {name: 'Washington St & Massachusetts Ave'},
    {name: 'Washington St & Worcester St'},
    {name: 'Washington St & E Newton St'},
    {name: 'Washington St & Union Pk'},
    {name: 'Washington St & E Berkeley St'},
    {name: 'Washington St & Herald St'},
    {name: 'Washington St & Tufts Med Ctr'},
    {name: 'Tremont St Opp Avery St'},
    {name: 'Temple Pl & Washington St'}
  ]
};

